file_path: us.json
output_file_path: output.csv

num_of_threads: 12
url: https://purchasealerts.visa.com/pas/apps/7d955368-76f3-4862-410a-18d406710101/issuerOptStatus
country_code: 840
retry_after: 1
offset: 0
limit: 1000

# Get data 
csrf_token: 0MVIxtRVWliSoW0Mdc4fbSIryZrvGGJCDt2zJoFP
country: UNITED STATES
brand: VISA
length: -1